import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import ClientToaster from "@/components/ui/client-toaster";

const noto = Noto_Sans_JP({
  weight: ["400", "500", "700"], // 必要な太さだけ
  preload: false,
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "kotayori",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      {/* ベース文字サイズは 14px 相当（text-sm）に */}
      <body
        className={`${noto.variable} font-sans text-sm antialiased min-h-screen overflow-x-auto overflow-y-auto`}
      >
        {children}
        <ClientToaster />
      </body>
    </html>
  );
}
